### PR TITLE
initial scraping test

### PR DESCRIPTION
**Pull request by jwaterfall**

### CODE REVIEW

**Review by bennyfreemantle — APPROVED** [review]

**Review by bennyfreemantle — APPROVED** [review]

**Review by bennyfreemantle — APPROVED** [review]

**Review by bennyfreemantle — APPROVED** [review]

**Review by bennyfreemantle — APPROVED** [review]

**Review by bennyfreemantle — APPROVED** [review]

**Review by bennyfreemantle — CHANGES_REQUESTED** [review]
crap mate

**Review by bennyfreemantle — COMMENTED** [review]
still sucks

**Review by bennyfreemantle — APPROVED** [review]
lgtm

**Review by Isaacboxall1 — APPROVED** [review]

**Review by Isaacboxall1 — CHANGES_REQUESTED** [review]
this smells of a rugpull :/

**Review by bennyfreemantle — COMMENTED** [review]
not great

**Pull request closed without merging**
